package com.jpaproject1.springjpa1.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

// 4 types of relations: a) OneToOne ,b)OneToMany ,c)ManyToOne ,D)ManyToMany

@Entity
@Getter
@Setter
public class Employee {
    @Id  //primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //id autogenerated
    private int id;
    private String name;
    private  String city;

    @JsonBackReference
    @NotNull
    @ManyToOne
    @JoinColumn(name = "dept_id")
    private Department department;

}
